server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Innocent-He/com.hgy.springcloud-config.git
          search-paths:
            - com.hgy.springcloud-config
      label: master
  rabbitmq:
    host: 192.168.19.128
    port: 5672
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
