server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #定义一个id，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh1
          #匹配后提供服务地址
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/query/**

        #定义一个id，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh2
          #匹配后提供服务地址
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求参数，名称为X-Request-Id，值为1024
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/discovery/**
            - After=2020-05-15T11:10:56.085+08:00[Asia/Shanghai]
#            - Cookie=username,hgy
#            - Head=X-Request-Id, \d+
#            - Host=**.gaoyunblog.com
#            - Method=GET
#            - Query=username,\d+
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
#       集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka