server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: openfign-80
  main:
    allow-bean-definition-overriding: true
#设置客户端超时时间(单位毫秒，OpenFeign默认支持Ribbon)
ribbon:
  #指的是建立连接后从服务器读取到可用资源的时间
  ReadTimeout: 5000
  #指的是建立连接所用的时间，适用于网络状况正常的情况下两端连接所用的时间
  ConnectTimeout: 5000
logging:
  level:
    #以什么级别打印feign接口的日志
    com.hgy.springcloud.config.PaymentFeignService: info